name: Deploy web to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      # Inject API URL for production
      - name: Inject env
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > apps/web/.env.production
      - run: pnpm -C apps/web build
      # SPA fallback: 404.html = index.html
      - run: cp apps/web/dist/index.html apps/web/dist/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4